### ISSUE TITLE
after 3 iterations loss will become nan

### ISSUE THREAD

**Issue by Yusin2Chen** [vidit98/graphconv#3]
when I trained network after 3 iterations, loss soon became nan, could you give me some help?Thank you very much

**Comment by vidit98** [comment]
Hi, did you change any of the settings? You can also try to change the learning rate

**Comment by Yusin2Chen** [comment]
> Hi, did you change any of the settings? You can also try to change the learning rate

I removed all cuda of graphLayer.py, because I can't run it successfully. After I change it, the output of gcu very easy to become nan after 3 iterrations, I totally don't understand, if you can give me some suggestions, that's would be very thanks.
